exports.up = async knex => knex.schema.createTable('guns', table => {
    table.increments('id')
    table.string('name')
        .unique()
        .notNullable()
    table.string('category')
        .notNullable()
    table.date('release_date')
    table.integer('price')
        .notNullable()
    table.string('used_by')
        .notNullable()
    table.integer('damage')
        .notNullable()
    table.integer('fire_rate')
        .notNullable()
    table.string('fire_mode')
        .notNullable()
    table.integer('magazine_capacity')
        .notNullable()
    table.integer('max_ammo')
        .notNullable()
    table.float('reload_time')
        .notNullable()
    table.integer('running_speed')
        .notNullable()
    
    table.timestamps(true, true)
})

exports.down = async knex => knex.schema.dropTable('guns')